### ISSUE TITLE
Web > Homepage > UI > Footer

### ISSUE THREAD

**Issue by milivayuz** [NM-COMMUNITY/issue-tracker#498]
<img width="959" alt="image" src="https://github.com/NM-COMMUNITY/issue-tracker/assets/156641922/a41a68b0-5422-4038-8f2f-81a2c9d64780">

no content in footer

**Comment by technicalbirdVayuz** [comment]
https://github.com/NM-COMMUNITY/issue-tracker/discussions/481

**Comment by technicalbirdVayuz** [comment]
Duplicate!
