### ISSUE TITLE
I am not following Gaon connection, and feed is coming from Gaon connection

### ISSUE THREAD

**Issue by MaroofTech** [NM-COMMUNITY/issue-tracker#569]
![Screenshot from 2024-04-16 12-50-58](https://github.com/NM-COMMUNITY/issue-tracker/assets/78342064/9d16cb4c-4fa1-46cf-a40f-44f3f9d2f11d)
![Screenshot from 2024-04-16 12-51-26](https://github.com/NM-COMMUNITY/issue-tracker/assets/78342064/22ff7e25-13ec-4f44-bfa4-9fd1067f7073)

**Comment by technicalbirdVayuz** [comment]
Consider it just like filter, its not coming as tab but it will be there in All (always)
