### ISSUE TITLE
Web > notification page > view post link not working

### ISSUE THREAD

**Issue by rahulmvayuz** [NM-COMMUNITY/issue-tracker#577]
![image](https://github.com/NM-COMMUNITY/issue-tracker/assets/164298543/26852d33-1ba3-4a44-b609-86360c1c649d)

**Comment by technicalbirdVayuz** [comment]
Please share your creds!

**Comment by rahulmvayuz** [comment]
> Please share your creds!

Email :- rahulmahto837@gmail.com
